name: X86-64 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Setup Ubuntu Environment
      run: sudo apt-get install -y xorriso nasm python3 git

    - name: Build x86-64
      run: make iso

    - name: Upload x86-64
      uses: actions/upload-artifact@v4
      with:
        name: kobold.iso
        path: kobold.iso
